// Network Request Actions
export const netReqAction = {
   FETCH_TRANSACTIONS_ENDPOINT: "FETCH_TRANSACTIONS_ENDPOINT",
   CREATE_TRANSACTION_ENDPOINT: "CREATE_TRANSACTION_ENDPOINT",
   UPDATE_TRANSACTION_ENDPOINT: "UPDATE_TRANSACTION_ENDPOINT",
   DELETE_TRANSACTION_ENDPOINT: "DELETE_TRANSACTION_ENDPOINT",
};

// Transaction Form Modes
export const formMode = {
   CREATE_TRANSACTION: "CREATE_TRANSACTION",
   EDIT_TRANSACTION: "EDIT_TRANSACTION",
};
